# Generated by Django 2.2.1 on 2019-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
