# Generated by Django 2.2.1 on 2019-06-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Score_evaluator', '0002_category_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryscore',
            name='score',
        ),
    ]
