# Generated by Django 2.2.1 on 2019-06-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Score_evaluator', '0003_remove_categoryscore_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
    ]
