# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_remove_profile_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
