# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-30 16:30
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_auto_20180830_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
