# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-31 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_auto_20180830_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='title',
        ),
    ]
